name = "bb"
version = "0.0.1"
description = "Black box testing framework for Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "horvathandris", repo = "bb" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
